### ISSUE TITLE
comment typo in contract 

### ISSUE THREAD

**Issue by minebuu** [MagicDragonDao/contracts#7]
https://github.com/MagicDragonDao/contracts/blob/6cafd9fd09b76593fb7eada9dde59a10b29783c2/contracts/AtlasMineStaker.sol#L81

/// @notice All deposit IDs fro a user, enumerated
-> /// @notice All deposit IDs from a user, enumerated

**Comment by millenarian** [comment]
Great spot 🕵️ 

See https://github.com/MagicDragonDao/contracts/commit/c61eb0d65cc7e1cac380b91e27c0d839acf36e5a for fix.
