### ISSUE TITLE
IERC1155Upgradeable should be changed to IERC721Upgradeable for legion 

### ISSUE THREAD

**Issue by minebuu** [MagicDragonDao/contracts#8]
Because the Legion NFT is ERC721, it should use IERC721Upgradeable instead of IERC1155Upgradeable. 
 
https://github.com/MagicDragonDao/contracts/blob/d8beff667754f4240267180d0b238554d901206c/contracts/AtlasMineStakerUpgradeable.sol#L588

So, Like this:

` IERC721Upgradeable(legionAddr).setApprovalForAll(address(mine), true); `

**Comment by millenarian** [comment]
:flushed: saved by overriding function selectors. Thanks for pointing this out!

Fixed in https://github.com/MagicDragonDao/contracts/commit/ba79584284db9857fb93f18df5ca355c4ad0ffe1.
